title: iocage
email: authors@iocage.io
sass:
  style: compact
  sass_dir: .

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

navigation:
  - name: "Home"
    url: "/"
  - name: "More on iocage"
    url: "/more-on-iocage/"
  - name: "Community"
    url: "/community/"
  - name: "Docs"
    url: "https://iocage.readthedocs.io/en/latest/index.html"
  - name: "GitHub"
    url: "https://github.com/iocage"
    icon: "github"
  - name: "iocage Google Group"
    url: "https://groups.google.com/forum/#!forum/iocage"
    icon: "google"